language: rust
sudo: false

matrix:
  fast_finish: true

  allow_failures:
    - env: [BENCH=read]
    - env: [BENCH=create]
    - env: [BENCH=iter]
    - env: [BENCH=resize]

  include:
    - rust: stable
    - rust: beta
    - rust: nightly

    # Benchmarks.
    - rust: nightly
      env:  [BENCH=read]
    - rust: nightly
      env:  [BENCH=create]
    - rust: nightly
      env:  [BENCH=iter]
    - rust: nightly
      env:  [BENCH=resize]

script:
  - if [[ ! -z "$BENCH" ]]; then
      cargo bench --features "nightly" --bench "$BENCH";
    elif [[ "$TRAVIS_RUST_VERSION" = "nightly" ]]; then
      cargo test --verbose --features nightly;
    else
      cargo test --verbose;
    fi
