[package]
name    = "picto"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "Image handling library."
repository  = "https://github.com/meh/rust-picto"
keywords    = ["image", "color"]

[dev-dependencies]
approx = "0.1"

[dependencies]
num     = "0.1"
palette = "0.2"

[dependencies.imagefmt]
version  = "4"
optional = true

[dependencies.png]
version  = "0.5"
optional = true

[dependencies.jpeg-decoder]
version  = "0.1"
optional = true

[features]
default = ["png", "jpeg", "bmp", "tga"]
nightly = []

jpeg = ["jpeg-decoder"]
bmp  = ["imagefmt"]
tga  = ["imagefmt"]
