[package]
name    = "picto"
version = "0.0.1"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "Image handling library."
repository  = "https://github.com/meh/rust-picto"
keywords    = ["image", "color"]

[dependencies]
num     = "0.1"
palette = "0.2"

[dependencies.png]
version  = "0.5"
optional = true

[features]
default = ["png"]
